### ISSUE TITLE
ui crash - when trying to click on a specific table

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#282]
The log below refers to the array issue but I am not sure if I have arrays here.
![image](https://user-images.githubusercontent.com/3479156/116383118-3ca79400-a81f-11eb-8581-0f56f2c37d3b.png)

Error from the log:
2021-04-28 11:16:49,503 [http-nio-auto-1-exec-3] INFO  c.d.c.s.controller.SIARDController - Conversion to SIARD successful, database: 730993c6-e322-4a56-85d4-13c9f1776a1b
2021-04-28 11:16:50,545 [http-nio-auto-1-exec-10] ERROR c.d.c.c.ClientConfigurationManager - [127.0.0.1] Requiring a shared property while they are not yet loaded

In the JVM log there is something about the arrays:
`com.databasepreservation.common.exceptions.ViewerException: Arrays are not yet supported.
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getColumnSolrName(ToolkitStructure2ViewerStructure.java:590)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getColumn(ToolkitStructure2ViewerStructure.java:530)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getColumns(ToolkitStructure2ViewerStructure.java:518)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getView(ToolkitStructure2ViewerStructure.java:286)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getViews(ToolkitStructure2ViewerStructure.java:275)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getSchema(ToolkitStructure2ViewerStructure.java:263)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getSchemas(ToolkitStructure2ViewerStructure.java:247)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getMetadata(ToolkitStructure2ViewerStructure.java:171)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getDatabase(ToolkitStructure2ViewerStructure.java:144)
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getDatabase(ToolkitStructure2ViewerStructure.java:123)
	at com.databasepreservation.common.server.controller.SIARDController.convertSIARDMetadataToSolr(SIARDController.java:621)
	at com.databasepreservation.common.server.controller.SIARDController.loadMetadataFromLocal(SIARDController.java:589)
	at com.databasepreservation.common.server.controller.SIARDController.loadMetadataFromLocal(SIARDController.java:582)
	at com.databasepreservation.common.api.v1.DatabaseResource.create(DatabaseResource.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

I am not sure if arrays are the issue or not but even without the array-support the application can not become unusable. At the moment the only possibility to go forward is to restart the app and not to click on that table.

**Comment by hmiguim** [comment]
Hi @Laurira can you share with me the metadata.xml file to take a look?

**Comment by Laurira** [comment]
I shared you the metadata.xml via e-mail.

**Comment by hmiguim** [comment]
I imported the SIARD with the metadata.xml you provided and could not replicate the error you encounter.
