### ISSUE TITLE
ui search - some keywords crash the application

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-ui#285]
Maybe this issue is related to https://github.com/keeps/dbptk-ui/issues/116 which should closed.

If I search Estonian female name  "Ene" from one of our Institutions database then everything works.
Now if I search Estonian male name "Are" then I will get 
![image](https://user-images.githubusercontent.com/3479156/117431630-20e47200-af32-11eb-9aa6-290551abc218.png)
and the application is not usable any more. It should be restarted.
I reproduced this issue three times in my database.

Although this issue is not occuring in Sakila.

The log is complaing something about empty arguments and memory leak.
```
2021-05-07 12:33:46,128 [http-nio-auto-1-exec-6] ERROR Uncaught - [127.0.0.1] Uncaught Exception: empty argument
java.lang.Throwable: null
	at Unknown.VQb(Throwable.java:68)
	at Unknown.fRb(Exception.java:29)
	at Unknown.hRb(RuntimeException.java:29)
	at Unknown.qmd(IllegalArgumentException.java:29)
	at Unknown.Xdc(JSONParser.java:201)
	at Unknown.hd(JSONParser.java:84)
	at Unknown.wn(MyAsyncDataProvider.java:63)
	at Unknown.wm(AsyncTableCell.java:166)
	at Unknown.mrb(AbstractRequestCallback.java:67)
	at Unknown.$8b(Request.java:250)
	at Unknown.q9b(RequestBuilder.java:412)
	at Unknown.anonymous(XMLHttpRequest.java:329)
	at Unknown.PZb(Impl.java:309)
	at Unknown.SZb(Impl.java:361)
	at Unknown.anonymous(Impl.java:78)
2021-05-07 12:34:00,418 [Thread-6] WARN  o.a.c.loader.WebappClassLoaderBase - The web application [ROOT] appears to have started a thread named [logback-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:


```

**Comment by Laurira** [comment]
I tested with dbptk-desktop-2.5.6-BETA1.AppImage on Ubuntu.
Seems to be fixed.

**Comment by hmiguim** [comment]
Fixed released on https://github.com/keeps/dbptk-ui/releases/tag/v2.5.6
