### ISSUE TITLE
Errors when stopping the application on Windows

### ISSUE THREAD

**Issue by chalkos** [keeps/dbptk-ui#84]
Description: 
When stopping the application, a error and stacktrace are displayed. This only happens 

Operative System:
Windows

**stop.bat** output:
```
"Shutting down Solr server"
No Solr nodes found to stop.
"Shutting down tomcat server"
Using CATALINA_BASE:   "C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\apache-tomcat"
Using CATALINA_HOME:   "C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\apache-tomcat"
Using CATALINA_TMPDIR: "C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\apache-tomcat\temp"
Using JRE_HOME:        "C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\jre\windows"
Using CLASSPATH:       "C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\apache-tomcat\bin\bootstrap.jar;C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\apache-tomcat\bin\tomcat-juli.jar"
02-Nov-2016 12:08:33.741 SEVERE [main] org.apache.catalina.startup.Catalina.stopServer Could not contact localhost:8005. Tomcat may not be running.
02-Nov-2016 12:08:33.749 SEVERE [main] org.apache.catalina.startup.Catalina.stopServer Catalina.stop:
java.net.ConnectException: Connection refused: connect
       at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:476)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:408)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:497)
"Cleaning up"
The system cannot find the file specified.
Could Not Find C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\dbptk-app-*.log.txt
Could Not Find C:\Users\ratsep\Desktop\DBVTK\dbvtk-0.1.0-windows\dbptk-report-*.txt
"Done."
Press any key to continue . . .
```

Reported by email by @Laurira

**Comment by luis100** [comment]
Closing due to inactivity.
